const constants = {
    ADD_USER: "ADD_USER",
    REMOVE_USER: "REMOVE_USER",
    MARK_CURRENT_USER: "MARK_CURRENT_USER",
    SHOW_CREATE_USER: "SHOW_CREATE_USER",
    FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
    FETCH_USERS_RESPONSE: "FETCH_USERS_RESPONSE",
    INVALIDATE_USERS: "INVALIDATE_USERS",
    RECEIVE_USERS: "RECEIVE_USERS",
    REQUEST_USERS: "REQUEST_USERS",
    SHOW_REMOVE_USER_MODAL: "SHOW_REMOVE_USER_MODAL",
    HIDE_REMOVE_USER_MODAL: "HIDE_REMOVE_USER_MODAL"
};

export default constants